### ISSUE TITLE
NAV bar needed

### ISSUE THREAD

**Issue by Kool-Cool** [Kool-Cool/Complete_flask_Webapp_Career#1]
TODO: NAV BAR

We need a new navigation bar for our website. Please create a new HTML file named NAV_BAR.html, which will contain the CSS and HTML code for the navigation bar. Make sure to follow the design guidelines and test your code before submitting.

#open for contributions
#need contributions
#contribution

This project is open for contributions from anyone who is interested. If you want to contribute, please check the GitHub issues page and pick an issue that you can work on. You can also create a new issue if you have an idea or a suggestion. Please follow the code of conduct and the contribution guidelines when submitting your pull requests.

**Comment by aharonYK** [comment]
Please assign me this issue I would like to contribute.

**Comment by Kool-Cool** [comment]
I would appreciate it
